CREATE TABLE credit_card_transactions (
    transaction_time NUMBER,
    v1 NUMBER,
    v2 NUMBER,
    v3 NUMBER,
    v4 NUMBER,
    v5 NUMBER,
    v6 NUMBER,
    v7 NUMBER,
    v8 NUMBER,
    v9 NUMBER,
    v10 NUMBER,
    v11 NUMBER,
    v12 NUMBER,
    v13 NUMBER,
    v14 NUMBER,
    v15 NUMBER,
    v16 NUMBER,
    v17 NUMBER,
    v18 NUMBER,
    v19 NUMBER,
    v20 NUMBER,
    v21 NUMBER,
    v22 NUMBER,
    v23 NUMBER,
    v24 NUMBER,
    v25 NUMBER,
    v26 NUMBER,
    v27 NUMBER,
    v28 NUMBER,
    amount NUMBER(15, 2),
    transaction_class NUMBER(1)
);